[package]
name = "esp-openthread"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-ieee802154 = { git = "https://github.com/esp-rs/esp-ieee802154.git", rev = "84fb4c6cb0deedcf330f181d88cbbe0e7383599e" }
esp-openthread-sys = { path = "../esp-openthread-sys" }
log = "0.4.17"
critical-section = "1.1.1"
fugit = "0.3.7"
bitflags = "2.4.0"
heapless = "0.8.0"
no-std-net = "0.6.0"

esp-hal = "0.16.1"

[features]
esp32c6 = [ "esp-ieee802154/esp32c6", "esp-hal/esp32c6"]
esp32h2 = [ "esp-ieee802154/esp32h2", "esp-hal/esp32h2"]
